server:
  port: 8080

  servlet:
    context-path: /privatebank/api


  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:postgresql://localhost/privatebankdb
    username: privatebank_user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  file:
    name: log/privatebank.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"